name: Publish to NPM
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/README.md'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm test --ci --coverage --maxWorkers=2
      - run: |
          npm config set registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
